# Default values for Smokeping chart.
# Update these values according to your requirements.
ingressHost: my.dynamic.ip.or.hostname

influxdb:
  image: influxdb:1.8
  adminUser: admin
  adminPassword: password
  db: smokeping

grafana:
  image: grafana/grafana:6.7.2
  adminPassword: admin
  ROOTURL: "https://{{ .Values.ingressHost }}/api/v1/namespaces/smokeping/services/http:grafana:80/proxy/?orgId=1"
  port: 80

smokeping:
  image: sjultra/smokeping:latest
  interval: 60
  host: ""

