# Default values for Smokeping chart.
# Update these values according to your requirements.
ingressHost: 184.174.32.74.sslip.io

influxdb:
  image: influxdb:1.7
  adminUser: admin
  adminPassword: password
  db: smokeping

grafana:
  image: grafana/grafana:6.7.2
  adminPassword: admin
  ROOTURL: https://184.174.32.74.sslip.io/api/v1/namespaces/smokeping/services/http:grafana:80/proxy/?orgId=1
  port: 80

smokeping:
  image: sjultra/smokeping:latest
  interval: 60
  host: ""

